//使用工具 http://tool.chinaz.com/Tools/Html_Js.aspx
//将公共部分转化为js 便于合作开发
document.writeln("<!-- 导航栏 -->");
document.writeln("<nav class=\'navbar navbar-default navbar-fixed-top\' role=\'navigation\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("            <!-- Brand and toggle get grouped for better mobile display -->");
document.writeln("            <div class=\'navbar-header\'>");
document.writeln("                <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\'");
document.writeln("                        data-target=\'#bs-example-navbar-collapse-1\'>");
document.writeln("                    <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("                    <span class=\'icon-bar\'></span>");
document.writeln("                    <span class=\'icon-bar\'></span>");
document.writeln("                    <span class=\'icon-bar\'></span>");
document.writeln("                </button>");
document.writeln("                <a class=\'navbar-brand\' href=\'#\'><img src=\'images/logo.png\'></a>");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <!-- Collect the nav links, forms, and other content for toggling -->");
document.writeln("            <div class=\'collapse navbar-collapse\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("                <ul class=\'nav navbar-nav main-nav  clear navbar-right \'>");
document.writeln("                    <li><a class=\'color_animation\' href=\'#top\'>喜迎二十大</a></li>");
document.writeln("                    <li><a class=\'color_animation\' href=\'history.html\'>以史为鉴</a></li>");
document.writeln("                    <li><a class=\'color_animation\' href=\'future.html\'>开创未来</a></li>");
document.writeln("                    <li><a class=\'color_animation\' href=\'work.html\'>埋头苦干</a></li>");
document.writeln("                    <li><a class=\'color_animation\' href=\'running.html\'>毅勇前行</a></li>");
document.writeln("                    <li><a class=\'color_animation\' href=\'doing.html\'>我们在行动</a></li>");
document.writeln("                </ul>");
document.writeln("            </div><!-- /.navbar-collapse -->");
document.writeln("        </div>");
document.writeln("    </div><!-- /.container-fluid -->");
document.writeln("</nav>");